commerce_payment.commerce_payment_gateway.plugin.fondy_redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    secret_key:
      type: string
      label: 'Secret key'
    preauth:
      type: boolean
      label: 'Preauth'
